### ISSUE TITLE
Option in `updatingByIdArrayMerger` to pick position to merge new items

### ISSUE THREAD

**Issue by daviscabral** [crudh/seamless-immutable-mergers#11]
Sometimes - like when in a `ScrollView` in a `react-native` app - I want to keep new items on top of the reducer. 

@crudh do you think that's a good addition to this extension?

**Comment by crudh** [comment]
@daviscabral sure, seems like a reasonable addition! I'll check the PR.

**Comment by crudh** [comment]
Fixed by #12 and released as 7.1.0. Thanks!
